<form method='post' action=''>
<table>
<tr><td>Match ID</td><td><input type="text" name="matchID" size="2" maxlength="2"></td></tr>
<tr><td>Team A</td><td><input type="text" name="teamA" maxlength="20"></td></tr>
<tr><td>Team B</td><td><input type="text" name="teamB" maxlength="20"></td></tr>
<tr><td>Toss</td><td><input type="radio" name="toss" value="1"> Team A<br><input type="radio" name="toss" value="2"> Team B</td></tr>
<tr><td>Choice</td><td><input type="radio" name="choice" value="Bat"> Batting<br><input type="radio" name="choice" value="Field"> Fielding</td></td></tr>
<tr><td>Umpires</td><td><input type="text" name="umpire1" maxlength="20"><br><input type="text" name="umpire2" maxlength="20"></td></tr>
</table>
<input type="submit" name="start" value="Start">
</form>
